# Nixpacks configuration for Railway  
# Use custom build script

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["corepack enable && yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "npx serve -s build -p $PORT"
